name: Generate Snake

on:
  # 1. 定时触发：每天 UTC 时间 0 点 (北京时间早上 8 点) 自动运行
  schedule:
    - cron: "0 0 * * *" 
  
  # 2. 手动触发：允许你在 Actions 页面手动点击按钮运行 (方便测试)
  workflow_dispatch:

# 必须设置写权限，否则无法将生成的图片推送到 output 分支
permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 生成贪吃蛇文件的核心步骤
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Colin0v0  # 你的用户名
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 把生成的文件推送到 output 分支
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
